# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-03 07:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(verbose_name='\u7ae0\u8282')),
                ('name', models.CharField(max_length=32, verbose_name='\u7ae0\u8282\u540d\u79f0')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='\u8bfe\u7a0b\u540d\u79f0')),
                ('course_img', models.CharField(max_length=64, verbose_name='\u8bfe\u7a0b\u56fe\u7247')),
                ('level', models.IntegerField(choices=[(1, '\u521d\u7ea7'), (2, '\u4e2d\u7ea7'), (3, '\u9ad8\u7ea7')], default=1, verbose_name='\u8bfe\u7a0b\u7b49\u7ea7')),
            ],
        ),
        migrations.CreateModel(
            name='CourseDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('why', models.CharField(max_length=255, verbose_name='\u4e3a\u4ec0\u4e48\u8981\u5b66')),
                ('slogon', models.CharField(max_length=255, verbose_name='\u53e3\u53f7')),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='vueproject.Course')),
                ('recommend_courses', models.ManyToManyField(related_name='rc', to='vueproject.Course', verbose_name='\u63a8\u8350\u8bfe\u7a0b')),
            ],
        ),
        migrations.AddField(
            model_name='chapter',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vueproject.Course', verbose_name='\u6240\u5c5e\u8bfe\u7a0b'),
        ),
    ]
